# Generated by Django 5.2.3 on 2025-09-01 17:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('deepseek', 'DeepSeek'), ('huggingface', 'Hugging Face'), ('grok', 'Grok'), ('gemini', 'Gemini')], default='gemini', max_length=20, unique=True, verbose_name='Pêşkêşkara AI')),
                ('is_active', models.BooleanField(default=False, verbose_name='Çalak')),
                ('api_key', models.CharField(blank=True, max_length=256, null=True, verbose_name='Miftê API')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dîroka Çêkirinê')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dîroka Nûkirinê')),
            ],
            options={
                'verbose_name': 'Veavakirina Pêşkêşkara AI',
                'verbose_name_plural': 'Veavakirina Pêşkêşkarên AI',
            },
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Atasozu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kelime', models.CharField(db_index=True, max_length=500, unique=True)),
                ('anlami', models.TextField(max_length=500)),
                ('ornek', models.TextField(blank=True, max_length=500)),
                ('eklenme_tarihi', models.DateTimeField(default=django.utils.timezone.now)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gotina Pêşiyan',
                'verbose_name_plural': 'Gotinên Pêşiyan',
                'ordering': ['kelime'],
            },
        ),
        migrations.CreateModel(
            name='Deyim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kelime', models.CharField(db_index=True, max_length=500, unique=True)),
                ('anlami', models.TextField(max_length=500)),
                ('ornek', models.TextField(blank=True, max_length=500)),
                ('eklenme_tarihi', models.DateTimeField(default=django.utils.timezone.now)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Îdîom',
                'verbose_name_plural': 'Îdîom',
                'ordering': ['kelime'],
            },
        ),
        migrations.CreateModel(
            name='AtasozuDeyimDetay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detay', models.TextField(max_length=1000, validators=[django.core.validators.MinLengthValidator(10)])),
                ('eklenme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('atasozu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detaylar', to='main.atasozu')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('deyim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detaylar', to='main.deyim')),
            ],
            options={
                'verbose_name': 'Berfirehiya Gotina Pêşiyan/Îdîom',
                'verbose_name_plural': 'Berfirehiyên Gotina Pêşiyan/Îdîom',
                'ordering': ['-eklenme_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='Katki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tur', models.CharField(choices=[('sarki', 'Gotinên Stranê'), ('kisi', 'Kes'), ('sozluk', 'Ferheng'), ('atasozu', 'Gotina Pêşiyan'), ('deyim', 'Îdîom'), ('yer_adi', 'Navê Cihê')], max_length=20)),
                ('icerik_id', models.PositiveIntegerField()),
                ('puan', models.PositiveIntegerField()),
                ('eklenme_tarihi', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='katkilar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Beşdarî',
                'verbose_name_plural': 'Beşdarîyan',
                'ordering': ['-eklenme_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='Kisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(db_index=True, max_length=100)),
                ('biyografi', models.TextField(max_length=20000)),
                ('eklenme_tarihi', models.DateTimeField(default=django.utils.timezone.now)),
                ('kategoriler', models.ManyToManyField(to='main.kategori')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kes',
                'verbose_name_plural': 'Kes',
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('eklenme_tarihi', models.DateTimeField(default=django.utils.timezone.now)),
                ('yil', models.PositiveIntegerField(blank=True, null=True, verbose_name='Sala Albûmê')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('kisi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albumler', to='main.kisi')),
            ],
            options={
                'verbose_name': 'Albûm',
                'verbose_name_plural': 'Albûm',
                'ordering': ['ad'],
                'unique_together': {('kisi', 'ad')},
            },
        ),
        migrations.CreateModel(
            name='KisiDetay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detay', models.TextField(max_length=20000, validators=[django.core.validators.MinLengthValidator(10)])),
                ('eklenme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('kisi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detaylar', to='main.kisi')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Berfirehiya Kesê',
                'verbose_name_plural': 'Berfirehiyên Kesan',
                'ordering': ['-eklenme_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('instagram_username', models.CharField(blank=True, max_length=30, null=True)),
                ('twitter_username', models.CharField(blank=True, max_length=30, null=True)),
                ('katki_puani', models.PositiveIntegerField(default=0)),
                ('account_status', models.CharField(choices=[('active', 'Çalak'), ('frozen', 'Cemidî'), ('deletion_scheduled', 'Jêbirin Hat Plankirî')], default='active', max_length=20)),
                ('scheduled_deletion_date', models.DateTimeField(blank=True, null=True)),
                ('preferred_language', models.CharField(blank=True, choices=[('tr', 'Tirkî'), ('ku', 'Kurdî'), ('en', 'Îngilîzî')], default='tr', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sarki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('sozler', models.TextField(max_length=10000)),
                ('link', models.URLField(blank=True, null=True)),
                ('eklenme_tarihi', models.DateTimeField(default=django.utils.timezone.now)),
                ('tur', models.CharField(blank=True, choices=[('pop', 'Pop'), ('klasik', 'Klasîk'), ('arabesk', 'Erebesk'), ('dengbej', 'Dengbêj'), ('halk', 'Muzîka Gelêrî'), ('serbest', 'Serbest'), ('rock', 'Rock'), ('rap', 'Rap'), ('hiphop', 'Hip Hop'), ('caz', 'Caz'), ('blues', 'Blues'), ('metal', 'Metal'), ('elektronik', 'Elektronîk'), ('tekno', 'Tekno'), ('rnb', 'R&B'), ('reggae', 'Reggae'), ('tasavvuf', 'Muzîka Dînî'), ('film', 'Muzîka Fîlmê'), ('çocuk', 'Muzîka Zarokan'), ('enstrümantal', 'Enstrûmental'), ('deneysel', 'Tecrubeyî')], max_length=50, verbose_name='Tür')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sarkilar', to='main.album')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stran',
                'verbose_name_plural': 'Stranan',
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='SarkiDetay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detay', models.TextField(max_length=1000, validators=[django.core.validators.MinLengthValidator(10)])),
                ('eklenme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sarki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detaylar', to='main.sarki')),
            ],
            options={
                'verbose_name': 'Berfirehiya Stranê',
                'verbose_name_plural': 'Berfirehiyên Stranan',
                'ordering': ['-eklenme_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='Sozluk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kelime', models.CharField(db_index=True, max_length=50, unique=True)),
                ('detay', models.TextField(max_length=500)),
                ('eklenme_tarihi', models.DateTimeField(default=django.utils.timezone.now)),
                ('tur', models.CharField(blank=True, choices=[('isim', 'Nav'), ('fiil', 'Lêker'), ('sifat', 'Navdêr'), ('zarf', 'Belavkar'), ('beyanvan', 'Beyanvan'), ('pevek', 'Pêvek'), ('giredek', 'Girêdek'), ('bang', 'Bang')], max_length=20)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ferheng',
                'verbose_name_plural': 'Ferheng',
                'ordering': ['kelime'],
            },
        ),
        migrations.CreateModel(
            name='SozlukDetay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detay', models.TextField(max_length=1000, validators=[django.core.validators.MinLengthValidator(10)])),
                ('eklenme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('kelime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detaylar', to='main.sozluk')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-eklenme_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Başlık',
                'verbose_name_plural': 'Başlıklar',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=10000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_entries', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='main.topic')),
            ],
            options={
                'verbose_name': 'Entry',
                'verbose_name_plural': "Entry'ler",
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='YerAdi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(db_index=True, max_length=100)),
                ('detay', models.TextField(blank=True, max_length=5000)),
                ('kategori', models.CharField(choices=[('il', 'Parêzgeh/Bajêr'), ('ilce', 'Navçe'), ('kasaba', 'Navçeyek/Qesebe'), ('belde', 'Gundgeha mezin'), ('koy', 'Gund')], max_length=20, verbose_name='Kategorî')),
                ('bolge', models.CharField(choices=[('bakur', 'Bakur'), ('basur', 'Başûr'), ('rojava', 'Rojava'), ('rojhilat', 'Rojhilat')], max_length=20, verbose_name='Herêma Kurdistanê')),
                ('enlem', models.FloatField(blank=True, null=True, verbose_name='Latîtûd')),
                ('boylam', models.FloatField(blank=True, null=True, verbose_name='Longîtûd')),
                ('eklenme_tarihi', models.DateTimeField(default=django.utils.timezone.now)),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='main.yeradi', verbose_name='Cihê Têkildar')),
            ],
            options={
                'verbose_name': 'Navê Cihê',
                'verbose_name_plural': 'Navên Cihan',
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='YerAdiDetay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detay', models.TextField(max_length=5000, validators=[django.core.validators.MinLengthValidator(10)])),
                ('eklenme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('yer_adi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detaylar', to='main.yeradi')),
            ],
            options={
                'verbose_name': 'Berfirehiya Navê Cihê',
                'verbose_name_plural': 'Berfirehiyên Navên Cihan',
                'ordering': ['-eklenme_tarihi'],
            },
        ),
    ]
