# Generated by Django 5.2 on 2026-07-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RuxPdfComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='İsim')),
                ('message', models.TextField(verbose_name='Mesaj/Yorum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Onaylı mı?')),
            ],
            options={
                'verbose_name': 'Rux PDF Yorumu',
                'verbose_name_plural': 'Rux PDF Yorumları',
                'ordering': ['-created_at'],
            },
        ),
    ]
