# Generated by Django 5.2.3 on 2025-09-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
