# Generated by Django 5.1.7 on 2025-05-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_remove_profile_account_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_status',
            field=models.CharField(choices=[('active', 'Aktif'), ('frozen', 'Dondurulmuş'), ('deletion_scheduled', 'Silinme Planlandı')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='scheduled_deletion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
