# Generated by Django 5.1.7 on 2025-05-01 21:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile_account_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('eklenme_tarihi', models.DateTimeField(default=django.utils.timezone.now)),
                ('kisi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albumler', to='main.kisi')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Albüm',
                'verbose_name_plural': 'Albümler',
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='Sarki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('sozler', models.TextField(max_length=10000)),
                ('link', models.URLField(blank=True, null=True)),
                ('eklenme_tarihi', models.DateTimeField(default=django.utils.timezone.now)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sarkilar', to='main.album')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Şarkı',
                'verbose_name_plural': 'Şarkılar',
                'ordering': ['ad'],
            },
        ),
    ]
