# Generated by Django 5.2.3 on 2025-09-01 20:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_entry_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='downvotes',
            field=models.ManyToManyField(blank=True, related_name='downvoted_topics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topic',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='upvoted_topics', to=settings.AUTH_USER_MODEL),
        ),
    ]
