# Generated by Django 5.1.7 on 2025-05-02 22:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_album_sarki'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atasozu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kelime', models.CharField(db_index=True, max_length=100, unique=True)),
                ('anlami', models.TextField(max_length=500)),
                ('ornek', models.TextField(blank=True, max_length=500)),
                ('eklenme_tarihi', models.DateTimeField(default=django.utils.timezone.now)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Atasözü',
                'verbose_name_plural': 'Atasözleri',
                'ordering': ['kelime'],
            },
        ),
        migrations.CreateModel(
            name='Deyim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kelime', models.CharField(db_index=True, max_length=100, unique=True)),
                ('anlami', models.TextField(max_length=500)),
                ('ornek', models.TextField(blank=True, max_length=500)),
                ('eklenme_tarihi', models.DateTimeField(default=django.utils.timezone.now)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deyim',
                'verbose_name_plural': 'Deyimler',
                'ordering': ['kelime'],
            },
        ),
    ]
