# Generated by Django 5.1.7 on 2025-03-31 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_commentvote_postvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentvote',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
