# Generated by Django 5.1.7 on 2025-05-03 18:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_atasozu_deyim'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='katki_puani',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Katki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tur', models.CharField(choices=[('sarki', 'Şarkı Sözü'), ('kisi', 'Kişi'), ('sozluk', 'Sözlük'), ('atasozu', 'Atasözü'), ('deyim', 'Deyim')], max_length=20)),
                ('icerik_id', models.PositiveIntegerField()),
                ('puan', models.PositiveIntegerField()),
                ('eklenme_tarihi', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='katkilar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Katkı',
                'verbose_name_plural': 'Katkılar',
                'ordering': ['-eklenme_tarihi'],
            },
        ),
    ]
