# Generated by Django 5.1.7 on 2025-03-31 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_commentvote_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentvote',
            name='views',
        ),
        migrations.AddField(
            model_name='comment',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
