# Generated by Django 5.1.7 on 2025-05-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_sozlukdetay'),
    ]

    operations = [
        migrations.AddField(
            model_name='sozluk',
            name='tur',
            field=models.CharField(blank=True, choices=[('isim', 'İsim'), ('fiil', 'Fiil'), ('sifat', 'Sıfat'), ('zarf', 'Zarf')], max_length=20),
        ),
    ]
