# Generated by Django 5.2.3 on 2025-09-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_category_topic_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='category',
        ),
        migrations.AddField(
            model_name='topic',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='topics', to='main.category'),
        ),
    ]
