# Generated by Django 5.1.7 on 2025-05-25 20:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_sozluk_tur'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='tur',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tür'),
        ),
        migrations.AddField(
            model_name='album',
            name='yil',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Albüm Yılı'),
        ),
        migrations.AlterUniqueTogether(
            name='album',
            unique_together={('kisi', 'ad')},
        ),
        migrations.CreateModel(
            name='SarkiDetay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detay', models.TextField(max_length=1000, validators=[django.core.validators.MinLengthValidator(10)])),
                ('eklenme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sarki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detaylar', to='main.sarki')),
            ],
            options={
                'verbose_name': 'Şarkı Detayı',
                'verbose_name_plural': 'Şarkı Detayları',
                'ordering': ['-eklenme_tarihi'],
            },
        ),
    ]
