# Generated by Django 5.1.7 on 2025-05-25 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_album_tur_album_yil_alter_album_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='tur',
        ),
        migrations.AddField(
            model_name='sarki',
            name='tur',
            field=models.CharField(blank=True, choices=[('pop', 'Pop'), ('klasik', 'Klasik'), ('arabesk', 'Arabesk'), ('dengbej', 'Dengbêj'), ('halk', 'Halk Müziği'), ('serbest', 'Serbest')], max_length=50, verbose_name='Tür'),
        ),
    ]
