# Generated by Django 5.1.7 on 2025-05-27 17:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_album_tur_sarki_tur'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AtasozuDeyimDetay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detay', models.TextField(max_length=1000, validators=[django.core.validators.MinLengthValidator(10)])),
                ('eklenme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('atasozu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detaylar', to='main.atasozu')),
                ('deyim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detaylar', to='main.deyim')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Atasözü/Deyim Detayı',
                'verbose_name_plural': 'Atasözü/Deyim Detayları',
                'ordering': ['-eklenme_tarihi'],
            },
        ),
    ]
