# Generated by Django 5.1.7 on 2025-05-27 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_atasozudeyimdetay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atasozu',
            name='kelime',
            field=models.CharField(db_index=True, max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='deyim',
            name='kelime',
            field=models.CharField(db_index=True, max_length=500, unique=True),
        ),
    ]
