# Generated by Django 5.2.3 on 2025-09-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='font_family',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
