# Generated by Django 5.1.7 on 2025-04-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_post_bookmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='comments_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='critiques_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='posts_visible',
            field=models.BooleanField(default=True),
        ),
    ]
