# Generated by Django 5.1.7 on 2025-06-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_atasozu_kelime_alter_deyim_kelime'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferred_language',
            field=models.CharField(blank=True, choices=[('tr', 'Türkçe'), ('ku', 'Kürtçe'), ('en', 'English')], default='tr', max_length=10),
        ),
    ]
