# Generated by Django 5.1.7 on 2025-04-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_profile_comments_visible_profile_critiques_visible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='embed_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
