# Generated by Django 5.2.3 on 2025-09-06 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_topicbookmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='topic',
        ),
    ]
