# Generated by Django 5.1.7 on 2025-04-23 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_post_embed_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='original_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
