# Generated by Django 5.2.3 on 2025-09-06 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_bookmark_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='biography',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
