# Generated by Django 5.1.7 on 2025-06-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_aiproviderconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiproviderconfig',
            name='provider',
            field=models.CharField(choices=[('deepseek', 'DeepSeek'), ('huggingface', 'Hugging Face'), ('grok', 'Grok'), ('gemini', 'Gemini')], default='gemini', max_length=20, unique=True, verbose_name='AI Sağlayıcısı'),
        ),
    ]
