# Generated by Django 5.1.7 on 2025-04-28 21:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20250423_2346'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sozluk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kelime', models.CharField(db_index=True, max_length=50, unique=True)),
                ('detay', models.TextField(max_length=500)),
                ('eklenme_tarihi', models.DateTimeField(default=django.utils.timezone.now)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sözlük',
                'verbose_name_plural': 'Sözlük',
                'ordering': ['kelime'],
            },
        ),
    ]
