# Generated by Django 5.2.3 on 2025-09-10 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_profile_biography'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiproviderconfig',
            options={'verbose_name': 'AI Sağlayıcı Yapılandırması', 'verbose_name_plural': 'AI Sağlayıcı Yapılandırmaları'},
        ),
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['ad'], 'verbose_name': 'Albüm', 'verbose_name_plural': 'Albümler'},
        ),
        migrations.AlterModelOptions(
            name='atasozu',
            options={'ordering': ['kelime'], 'verbose_name': 'Atasözü', 'verbose_name_plural': 'Atasözleri'},
        ),
        migrations.AlterModelOptions(
            name='atasozudeyimdetay',
            options={'ordering': ['-eklenme_tarihi'], 'verbose_name': 'Atasözü/Deyim Detayı', 'verbose_name_plural': 'Atasözü/Deyim Detayları'},
        ),
        migrations.AlterModelOptions(
            name='deyim',
            options={'ordering': ['kelime'], 'verbose_name': 'Deyim', 'verbose_name_plural': 'Deyimler'},
        ),
        migrations.AlterModelOptions(
            name='katki',
            options={'ordering': ['-eklenme_tarihi'], 'verbose_name': 'Katkı', 'verbose_name_plural': 'Katkılar'},
        ),
        migrations.AlterModelOptions(
            name='kisi',
            options={'ordering': ['ad'], 'verbose_name': 'Kişi', 'verbose_name_plural': 'Kişiler'},
        ),
        migrations.AlterModelOptions(
            name='kisidetay',
            options={'ordering': ['-eklenme_tarihi'], 'verbose_name': 'Kişi Detayı', 'verbose_name_plural': 'Kişi Detayları'},
        ),
        migrations.AlterModelOptions(
            name='sarki',
            options={'ordering': ['ad'], 'verbose_name': 'Şarkı', 'verbose_name_plural': 'Şarkılar'},
        ),
        migrations.AlterModelOptions(
            name='sarkidetay',
            options={'ordering': ['-eklenme_tarihi'], 'verbose_name': 'Şarkı Detayı', 'verbose_name_plural': 'Şarkı Detayları'},
        ),
        migrations.AlterModelOptions(
            name='sozluk',
            options={'ordering': ['kelime'], 'verbose_name': 'Sözlük', 'verbose_name_plural': 'Sözlük'},
        ),
        migrations.AlterModelOptions(
            name='yeradi',
            options={'ordering': ['ad'], 'verbose_name': 'Yer Adı', 'verbose_name_plural': 'Yer Adları'},
        ),
        migrations.AlterModelOptions(
            name='yeradidetay',
            options={'ordering': ['-eklenme_tarihi'], 'verbose_name': 'Yer Adı Detayı', 'verbose_name_plural': 'Yer Adı Detayları'},
        ),
        migrations.AddField(
            model_name='profile',
            name='user_role',
            field=models.CharField(choices=[('user', 'Kullanıcı'), ('writer', 'Yazar'), ('moderator', 'Moderatör'), ('admin', 'Admin'), ('super_admin', 'Süper Admin')], default='user', max_length=20, verbose_name='Kullanıcı Rolü'),
        ),
        migrations.AlterField(
            model_name='aiproviderconfig',
            name='api_key',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='API Anahtarı'),
        ),
        migrations.AlterField(
            model_name='aiproviderconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='aiproviderconfig',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Aktif'),
        ),
        migrations.AlterField(
            model_name='aiproviderconfig',
            name='provider',
            field=models.CharField(choices=[('deepseek', 'DeepSeek'), ('huggingface', 'Hugging Face'), ('grok', 'Grok'), ('gemini', 'Gemini')], default='gemini', max_length=20, unique=True, verbose_name='AI Sağlayıcısı'),
        ),
        migrations.AlterField(
            model_name='aiproviderconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi'),
        ),
        migrations.AlterField(
            model_name='album',
            name='yil',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Albüm Yılı'),
        ),
        migrations.AlterField(
            model_name='katki',
            name='tur',
            field=models.CharField(choices=[('sarki', 'Şarkı Sözleri'), ('kisi', 'Kişi'), ('sozluk', 'Sözlük'), ('atasozu', 'Atasözü'), ('deyim', 'Deyim'), ('yer_adi', 'Yer Adı')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='account_status',
            field=models.CharField(choices=[('active', 'Aktif'), ('frozen', 'Dondurulmuş'), ('deletion_scheduled', 'Silinme Planlandı')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='preferred_language',
            field=models.CharField(blank=True, choices=[('tr', 'Türkçe'), ('ku', 'Kürtçe'), ('en', 'İngilizce')], default='tr', max_length=10),
        ),
        migrations.AlterField(
            model_name='sarki',
            name='tur',
            field=models.CharField(blank=True, choices=[('pop', 'Pop'), ('klasik', 'Klasik'), ('arabesk', 'Arabesk'), ('dengbej', 'Dengbej'), ('halk', 'Halk Müziği'), ('serbest', 'Serbest'), ('rock', 'Rock'), ('rap', 'Rap'), ('hiphop', 'Hip Hop'), ('caz', 'Caz'), ('blues', 'Blues'), ('metal', 'Metal'), ('elektronik', 'Elektronik'), ('tekno', 'Tekno'), ('rnb', 'R&B'), ('reggae', 'Reggae'), ('tasavvuf', 'Dini Müzik'), ('film', 'Film Müziği'), ('çocuk', 'Çocuk Müziği'), ('enstrümantal', 'Enstrümantal'), ('deneysel', 'Deneysel')], max_length=50, verbose_name='Tür'),
        ),
        migrations.AlterField(
            model_name='sozluk',
            name='tur',
            field=models.CharField(blank=True, choices=[('isim', 'İsim'), ('fiil', 'Fiil'), ('sifat', 'Sıfat'), ('zarf', 'Zarf'), ('beyanvan', 'Beyanvan'), ('pevek', 'Bağlaç'), ('giredek', 'Bağlaç'), ('bang', 'Ünlem')], max_length=20),
        ),
        migrations.AlterField(
            model_name='yeradi',
            name='bolge',
            field=models.CharField(choices=[('bakur', 'Bakur'), ('basur', 'Başûr'), ('rojava', 'Rojava'), ('rojhilat', 'Rojhilat')], max_length=20, verbose_name='Kürdistan Bölgesi'),
        ),
        migrations.AlterField(
            model_name='yeradi',
            name='boylam',
            field=models.FloatField(blank=True, null=True, verbose_name='Boylam'),
        ),
        migrations.AlterField(
            model_name='yeradi',
            name='enlem',
            field=models.FloatField(blank=True, null=True, verbose_name='Enlem'),
        ),
        migrations.AlterField(
            model_name='yeradi',
            name='kategori',
            field=models.CharField(choices=[('il', 'İl/Şehir'), ('ilce', 'İlçe'), ('kasaba', 'Kasaba'), ('belde', 'Belde'), ('koy', 'Köy')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='yeradi',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='main.yeradi', verbose_name='İlgili Yer'),
        ),
    ]
