# Generated by Django 5.1.7 on 2025-09-13 23:18

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_aiproviderconfig_options_alter_album_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=200, unique=True, validators=[main.models.validate_title_text_only]),
        ),
    ]
