# Generated by Django 5.1.7 on 2025-07-14 21:28

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_kisidetay'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='katki',
            name='tur',
            field=models.CharField(choices=[('sarki', 'Şarkı Sözü'), ('kisi', 'Kişi'), ('sozluk', 'Sözlük'), ('atasozu', 'Atasözü'), ('deyim', 'Deyim'), ('yer_adi', 'Yer Adı'), ('yer_adi_detay', 'Yer Adı Detayı')], max_length=20),
        ),
        migrations.CreateModel(
            name='YerAdi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(db_index=True, max_length=100)),
                ('detay', models.TextField(blank=True, max_length=5000)),
                ('kategori', models.CharField(choices=[('il', 'İl'), ('ilce', 'İlçe'), ('kasaba', 'Kasaba'), ('belde', 'Belde'), ('koy', 'Köy')], max_length=20, verbose_name='Kategori')),
                ('bolge', models.CharField(choices=[('bakur', 'Bakur'), ('basur', 'Başûr'), ('rojava', 'Rojava'), ('rojhilat', 'Rojhilat')], max_length=20, verbose_name='Kürdistan Bölgesi')),
                ('enlem', models.FloatField(blank=True, null=True, verbose_name='Enlem')),
                ('boylam', models.FloatField(blank=True, null=True, verbose_name='Boylam')),
                ('eklenme_tarihi', models.DateTimeField(default=django.utils.timezone.now)),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Yer Adı',
                'verbose_name_plural': 'Yer Adları',
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='YerAdiDetay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detay', models.TextField(max_length=5000, validators=[django.core.validators.MinLengthValidator(10)])),
                ('eklenme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('yer_adi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detaylar', to='main.yeradi')),
            ],
            options={
                'verbose_name': 'Yer Adı Detayı',
                'verbose_name_plural': 'Yer Adı Detayları',
                'ordering': ['-eklenme_tarihi'],
            },
        ),
    ]
