# Generated by Django 5.1.7 on 2025-07-22 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_katki_tur_yeradi_yeradidetay'),
    ]

    operations = [
        migrations.AddField(
            model_name='yeradi',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='main.yeradi', verbose_name='Bağlı Olduğu Yer'),
        ),
    ]
