# Generated by Django 5.1.7 on 2025-09-13 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_add_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
