# Generated by Django 5.1.7 on 2025-10-04 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_entry_code_alter_topic_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('interaction', '💬 Etkileşim'), ('social', '👥 Sosyal'), ('content', '📝 İçerik'), ('important', '🔥 Önemli')], default='interaction', max_length=20),
        ),
    ]
