# Generated by Django 5.1.7 on 2025-10-04 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_notification_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dark_mode',
            field=models.BooleanField(default=False, verbose_name='Karanlık Mod'),
        ),
    ]
