# Generated by Django 5.2.3 on 2025-10-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_notification_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='facebook_username',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Facebook Kullanıcı Adı'),
        ),
        migrations.AddField(
            model_name='profile',
            name='github_username',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='GitHub Kullanıcı Adı'),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True, verbose_name='LinkedIn Profili'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tiktok_username',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='TikTok Kullanıcı Adı'),
        ),
        migrations.AddField(
            model_name='profile',
            name='website_url',
            field=models.URLField(blank=True, null=True, verbose_name='Kişisel Website'),
        ),
        migrations.AddField(
            model_name='profile',
            name='youtube_url',
            field=models.URLField(blank=True, null=True, verbose_name='YouTube Kanalı'),
        ),
    ]
