# Generated by Django 5.1.7 on 2025-10-06 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_profile_facebook_username_profile_github_username_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE main_profile DROP COLUMN IF EXISTS dark_mode;",
            reverse_sql="ALTER TABLE main_profile ADD COLUMN dark_mode BOOLEAN DEFAULT FALSE;"
        ),
    ]