# Generated by Django 5.1.7 on 2025-10-06 20:25

from django.db import migrations
from django.db import connection

def remove_dark_mode_column(apps, schema_editor):
    """Veritabanı türüne göre dark_mode kolonu sil"""
    if connection.vendor == 'postgresql':
        # PostgreSQL için
        schema_editor.execute("ALTER TABLE main_profile DROP COLUMN IF EXISTS dark_mode;")
    elif connection.vendor == 'sqlite':
        # SQLite için - kolon varsa sil
        try:
            schema_editor.execute("PRAGMA table_info(main_profile);")
            # SQLite'da kolon silme işlemi daha karmaşık, bu yüzden atla
            pass
        except:
            pass

def reverse_remove_dark_mode_column(apps, schema_editor):
    """Geri alma işlemi"""
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_profile_facebook_username_profile_github_username_and_more'),
    ]

    operations = [
        migrations.RunPython(
            remove_dark_mode_column,
            reverse_remove_dark_mode_column
        ),
    ]