# Generated by Django 5.2.3 on 2025-10-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_profile_dark_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='sozluk',
            name='ingilizce_karsiligi',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='İngilizce Karşılığı'),
        ),
        migrations.AddField(
            model_name='sozluk',
            name='turkce_karsiligi',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Türkçe Karşılığı'),
        ),
    ]
