# Generated by Django 5.1.7 on 2025-10-06 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_profile_dark_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='dark_mode',
        ),
    ]
