# Generated by Django 5.1.7 on 2025-10-24 19:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_sozluk_ingilizce_karsiligi_sozluk_turkce_karsiligi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sarki',
            options={},
        ),
        migrations.AddField(
            model_name='sarki',
            name='dil',
            field=models.CharField(choices=[('ku', 'Kürtçe'), ('tr', 'Türkçe'), ('en', 'İngilizce'), ('ar', 'Arapça'), ('fa', 'Farsça')], default='ku', max_length=10, verbose_name='Dil'),
        ),
        migrations.CreateModel(
            name='SarkiGrubu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('eklenme_tarihi', models.DateTimeField(default=django.utils.timezone.now)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sarki_gruplari', to='main.album')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Şarkı Grubu',
                'verbose_name_plural': 'Şarkı Grupları',
                'unique_together': {('album', 'ad')},
            },
        ),
        migrations.AddField(
            model_name='sarki',
            name='sarki_grubu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dil_versiyonlari', to='main.sarkigrubu'),
        ),
        migrations.AlterUniqueTogether(
            name='sarki',
            unique_together={('sarki_grubu', 'dil')},
        ),
        migrations.RemoveField(
            model_name='sarki',
            name='ad',
        ),
        migrations.RemoveField(
            model_name='sarki',
            name='album',
        ),
        migrations.RemoveField(
            model_name='sarki',
            name='eklenme_tarihi',
        ),
        migrations.RemoveField(
            model_name='sarki',
            name='kullanici',
        ),
        migrations.RemoveField(
            model_name='sarki',
            name='link',
        ),
        migrations.RemoveField(
            model_name='sarki',
            name='tur',
        ),
    ]
