# Generated by Django 5.1.7 on 2025-10-24 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_sarki_options_sarki_dil_sarkigrubu_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sarki',
            options={'verbose_name': 'Şarkı', 'verbose_name_plural': 'Şarkılar'},
        ),
    ]
