# Generated by Django 5.1.7 on 2025-10-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_sarki_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kisi',
            options={'ordering': ['ad'], 'verbose_name': 'Kişi/Grup', 'verbose_name_plural': 'Kişiler/Gruplar'},
        ),
        migrations.AddField(
            model_name='kisi',
            name='aktif_yillar',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Aktif Yıllar'),
        ),
        migrations.AddField(
            model_name='kisi',
            name='cinsiyet',
            field=models.CharField(choices=[('erkek', 'Erkek'), ('kadin', 'Kadın'), ('belirtilmemis', 'Belirtilmemiş')], default='belirtilmemis', max_length=20, verbose_name='Cinsiyet'),
        ),
        migrations.AddField(
            model_name='kisi',
            name='dogum_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi'),
        ),
        migrations.AddField(
            model_name='kisi',
            name='dogum_yeri',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Doğum Yeri'),
        ),
        migrations.AddField(
            model_name='kisi',
            name='instagram',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='kisi',
            name='kisi_turu',
            field=models.CharField(choices=[('kisi', 'Kişi'), ('grup', 'Grup/Topluluk'), ('kurum', 'Kurum/Organizasyon')], default='kisi', max_length=20, verbose_name='Kişi Türü'),
        ),
        migrations.AddField(
            model_name='kisi',
            name='meslek',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Meslek/Alan'),
        ),
        migrations.AddField(
            model_name='kisi',
            name='olum_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='Ölüm Tarihi'),
        ),
        migrations.AddField(
            model_name='kisi',
            name='twitter',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Twitter'),
        ),
        migrations.AddField(
            model_name='kisi',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
        migrations.AddField(
            model_name='kisi',
            name='youtube',
            field=models.URLField(blank=True, null=True, verbose_name='YouTube'),
        ),
    ]
