# Generated by Django 5.1.7 on 2025-10-25 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_kisi_options_kisi_aktif_yillar_kisi_cinsiyet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kisi',
            name='bagli_grup',
            field=models.ForeignKey(blank=True, limit_choices_to={'kisi_turu__in': ['grup', 'kurum']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uyeler', to='main.kisi', verbose_name='Bağlı Grup/Kurum'),
        ),
    ]
