# Generated by Django 5.1.7 on 2025-10-25 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_kisi_bagli_grup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kisi',
            name='dogum_yeri',
        ),
        migrations.AddField(
            model_name='kisi',
            name='dogum_yeri_secim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.yeradi', verbose_name='Doğum Yeri (Listeden Seç)'),
        ),
        migrations.AddField(
            model_name='kisi',
            name='dogum_yeri_serbest',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Doğum Yeri (Serbest Metin)'),
        ),
    ]
