# Generated by Django 4.2.7 on 2024-01-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_remove_kisi_dogum_yeri_kisi_dogum_yeri_secim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atasozu',
            name='slug',
            field=models.SlugField(blank=True, null=True, max_length=200),
        ),
        migrations.AddField(
            model_name='deyim',
            name='slug',
            field=models.SlugField(blank=True, null=True, max_length=200),
        ),
        migrations.AddField(
            model_name='kisi',
            name='slug',
            field=models.SlugField(blank=True, null=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sarki',
            name='slug',
            field=models.SlugField(blank=True, null=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sozluk',
            name='slug',
            field=models.SlugField(blank=True, null=True, max_length=200),
        ),
        migrations.AddField(
            model_name='yeradi',
            name='slug',
            field=models.SlugField(blank=True, null=True, max_length=200),
        ),
    ]