# Generated by Django 5.1.7 on 2025-10-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_add_slug_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sarki',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Şarkı Linki (YouTube, Spotify vs.)'),
        ),
    ]
